# Generated by Django 5.2.17 on 2026-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_review_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
